### ISSUE TITLE
./zxing  shell script starts the jruby and Jruby server terminates after 2sec .

### ISSUE THREAD

**Issue by manasatr** [smparkes/zxing.rb#4]
Jruby die as soon as it starts.
When it dies I am seeing the below stacktrace

evaluate at /Library/Ruby/Gems/1.8/gems/bundler-1.2.3/lib/bundler/dsl.rb:12
       build at /Library/Ruby/Gems/1.8/gems/bundler-1.2.3/lib/bundler/definition.rb:18
  definition at /Library/Ruby/Gems/1.8/gems/bundler-1.2.3/lib/bundler.rb:144
       setup at /Library/Ruby/Gems/1.8/gems/bundler-1.2.3/lib/bundler.rb:112
      (root) at /Library/Ruby/Gems/1.8/gems/bundler-1.2.3/lib/bundler/setup.rb:17
     require at org/jruby/RubyKernel.java:1085
      (root) at file:/Users/mghanta/.gem/ruby/1.8/ruby/1.8/gems/jruby-jars-1.7.11/lib/jruby-stdlib-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1

**Comment by smparkes** [comment]
Right project? There's no zxing shell script in this project.

**Comment by manasatr** [comment]
file :  lib/zxing/client.rb  

line below  starts the jruby process and it is terminating immediately 
 remote_client = IO.popen("#{ZXing::BIN}  #{port}")

**Comment by smparkes** [comment]
You're looking for https://github.com/ecin/zxing.rb
